name: job_timer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #third_party_dependencies:
  #modular
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  asuka: ^2.0.0+1

  #firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3

  #state_management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #database
  isar: 2.5.0
  isar_flutter_libs: 2.5.0 # contains the binaries

  validatorless: ^1.2.1
  fl_chart: ^0.51.0
  equatable: ^2.0.3
  path_provider: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: 2.5.0
  build_runner: ^2.1.11


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Freeler
      fonts:
        - asset: assets/fonts/Freeler.ttf
        
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
